on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/src.fsproj

    - name: Build project
      run: dotnet build ./src

    - name: Set DOTNET_ROLL_FORWARD
      run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV

    - name: Lint
      run: |
        dotnet tool install -g dotnet-fsharplint
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        dotnet fsharplint lint src/*.fs

    - name: Formatter
      run: |
        dotnet tool install -g fantomas-tool
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        fantomas ./src/*.fs    
        
    - name: Run project
      run: dotnet run --project ./src

    - name: Test project
      run: |
          dotnet restore tests/tests.fsproj
          dotnet build ./tests
          dotnet test --logger "console;verbosity=detailed" ./tests
